services:
  - type: web
    name: manhwaread-web
    runtime: node
    plan: free
    region: frankfurt
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
